# Generated by Django 4.2.3 on 2023-09-27 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='image',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='Post'),
        ),
        migrations.CreateModel(
            name='DeletedImage',
            fields=[
            ],
            options={
                'verbose_name': 'Deleted image',
                'verbose_name_plural': 'Deleted images',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('posts.image',),
            managers=[
                ('objects', posts.models.SoftDeleted()),
            ],
        ),
        migrations.CreateModel(
            name='DeletedPost',
            fields=[
            ],
            options={
                'verbose_name': 'Deleted post',
                'verbose_name_plural': 'Deleted posts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('posts.post',),
            managers=[
                ('objects', posts.models.SoftDeleted()),
            ],
        ),
        migrations.CreateModel(
            name='DeletedReply',
            fields=[
            ],
            options={
                'verbose_name': 'Deleted reply',
                'verbose_name_plural': 'Deleted replies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('posts.reply',),
            managers=[
                ('objects', posts.models.SoftDeleted()),
            ],
        ),
    ]
