# Generated by Django 4.2.2 on 2023-06-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_slug',
            field=models.SlugField(unique=True, verbose_name='post slug'),
        ),
    ]
