# Generated by Django 4.2.2 on 2023-06-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='soft_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='soft_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='soft_delete',
            field=models.BooleanField(default=False),
        ),
    ]
