# Generated by Django 4.2.2 on 2023-06-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_post_id_image_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='post',
            new_name='post_id',
        ),
    ]
