# Generated by Django 4.2.2 on 2023-06-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='soft_delete',
            field=models.BooleanField(default=False),
        ),
    ]
