# Generated by Django 4.2.2 on 2023-06-27 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tags', '0003_alter_taggeditem_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggeditem',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='Post ID'),
        ),
        migrations.AlterField(
            model_name='taggeditem',
            name='tag_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_from', to='contenttypes.contenttype', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='taggeditem',
            name='user',
            field=models.PositiveIntegerField(verbose_name='User ID'),
        ),
    ]
