# Generated by Django 4.2.2 on 2023-06-27 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_alter_taggeditem_object_id_alter_taggeditem_tag_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggeditem',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_tag', to='tags.tag'),
        ),
    ]
