# Generated by Django 4.2.2 on 2023-06-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.FileField(upload_to='profilepic/', verbose_name='User profile picture'),
        ),
    ]
