# Generated by Django 4.2.3 on 2023-09-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_slug',
            field=models.SlugField(default='c5eaa8acb63b45a990b0b1510af8360d', verbose_name='slug'),
        ),
    ]
