# Generated by Django 4.2.2 on 2023-06-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_slug',
            field=models.SlugField(default='13ee135bc6ac46a38d1b3744a1c04507', unique=True, verbose_name='User slug'),
        ),
    ]
