# Generated by Django 4.2.2 on 2023-06-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0002_alter_useraccount_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='soft_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='soft_delete',
            field=models.BooleanField(default=False),
        ),
    ]
