# Generated by Django 4.2.2 on 2023-06-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0002_alter_useraccount_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_slug',
            field=models.SlugField(default='12f19d37b382435481654e67dfac8f85', unique=True, verbose_name='User slug'),
        ),
    ]
