# Generated by Django 4.2.2 on 2023-06-19 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0003_relation_soft_delete_useraccount_soft_delete'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='useraccount',
            managers=[
            ],
        ),
    ]
