# Generated by Django 4.2.2 on 2023-06-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0004_alter_useraccount_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_slug',
            field=models.SlugField(default='4940415d253141ddb30d7ad8ac4b8476', unique=True, verbose_name='User slug'),
        ),
    ]
