# Generated by Django 4.2.2 on 2023-06-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0005_alter_useraccount_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_slug',
            field=models.SlugField(default='13806042e2294917b6d9bb8434f341ca', unique=True, verbose_name='User slug'),
        ),
    ]
