# Generated by Django 4.2.2 on 2023-06-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0006_alter_useraccount_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='static/profilepics/', verbose_name='User profile picture'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user_slug',
            field=models.SlugField(default='cc89f4e61d2b45b4bfd6f0be49503782', unique=True, verbose_name='User slug'),
        ),
    ]
