# Generated by Django 4.2.2 on 2023-06-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0007_alter_useraccount_image_alter_useraccount_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='profilepics/', verbose_name='User profile picture'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user_slug',
            field=models.SlugField(default='ae0264cd05ff48e7953b406349967b0a', unique=True, verbose_name='User slug'),
        ),
    ]
