# Generated by Django 4.2.2 on 2023-06-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0008_alter_useraccount_image_alter_useraccount_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_slug',
            field=models.SlugField(default='useraccounts.UserAccount.username', unique=True, verbose_name='User slug'),
        ),
    ]
