# Generated by Django 4.2.2 on 2023-06-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0009_alter_useraccount_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_slug',
            field=models.SlugField(default={'__annotations__': {}, '__doc__': None, '__module__': 'useraccounts.models', '__name__': 'generate_slug', '__qualname__': 'UserAccount.generate_slug'}, unique=True, verbose_name='User slug'),
        ),
    ]
