# Generated by Django 4.2.2 on 2023-06-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0011_alter_useraccount_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_slug',
            field=models.SlugField(default='cf8fe00cab7d4c44ba04591ea6ca0845', unique=True, verbose_name='User slug'),
        ),
    ]
