# Generated by Django 4.2.2 on 2023-06-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0012_alter_useraccount_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_slug',
            field=models.SlugField(default='aa279f2768f04e52bc5f1d5a7ab954fe', unique=True, verbose_name='User slug'),
        ),
    ]
