# Generated by Django 4.2.2 on 2023-06-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0013_alter_useraccount_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_slug',
            field=models.SlugField(default='3bf89661d1384245ac6ec88d08f9f08f', unique=True, verbose_name='User slug'),
        ),
    ]
