# Generated by Django 4.2.2 on 2023-06-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0014_alter_useraccount_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_slug',
            field=models.SlugField(default='53da61258ac74847907773efdb6ba3d6', unique=True, verbose_name='User slug'),
        ),
    ]
