# Generated by Django 4.2.2 on 2023-07-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0015_alter_useraccount_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_slug',
            field=models.SlugField(default='ec3d682381604d0092bbc1615bcf4b11', unique=True, verbose_name='User slug'),
        ),
    ]
