# Generated by Django 4.2.2 on 2023-07-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0016_alter_useraccount_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_slug',
            field=models.SlugField(default='8a02bc069ea5451ba334f6b493b7b173', unique=True, verbose_name='User slug'),
        ),
    ]
