# Generated by Django 4.2.2 on 2023-07-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0018_alter_useraccount_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_slug',
            field=models.SlugField(default='b5106cf453154118870ec7f8d4a174b0', unique=True, verbose_name='User slug'),
        ),
    ]
