# Generated by Django 4.2.2 on 2023-07-03 15:52

from django.db import migrations, models
import useraccounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0019_alter_useraccount_user_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='useraccount',
            managers=[
                ('objects', useraccounts.models.UserAccountManager()),
            ],
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user_slug',
            field=models.SlugField(default='584a4fbcf4b740ee821b2c9fb78ee991', unique=True, verbose_name='User slug'),
        ),
    ]
