# Generated by Django 4.2.3 on 2023-09-27 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_status', models.CharField(choices=[('LIKE', 'Like'), ('DISLIKE', 'Dislike')], max_length=50, verbose_name='Reaction status')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID')),
                ('user', models.PositiveIntegerField(verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at:')),
                ('reaction_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content type')),
                ('reaction_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction_from', to='contenttypes.contenttype', verbose_name='Content type')),
            ],
        ),
    ]
